config/routes.rb
Rails.application.routes.draw do
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider

  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :users, only: %i[new create]
  resources :posts, only: %i[index new create show destroy] do
    collection do 
      get 'search'
    end
    
    member do
      get 'vote'
    end
    resources :comments, only: %i[create destroy]
    resources :votes, only: %i[create]
    mount ActionCable.server => '/cable'
    resources :comments, only: %i[create destroy]
  end

  resources :restaurants, only: %i[index] do
    collection do
      get 'search'
    end
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
  validates :body, length: { maximum: 100 }

  def own?(user)
    self.user == user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      ActionCable.server.broadcast 'comment_channel', { content: render_comment(@comment) }
    else
      flash[:danger] = 'コメントの投稿に失敗しました。'
      redirect_to post_path(@comment.post), status: :unprocessable_entity
    end
  end
  
  def destroy
    @comment = current_user.comments.find(params[:id])
    @post = @comment.post
    @comment.destroy
    flash[:success] = 'コメントを削除しました。'
    redirect_to post_path(@comment.post), status: :see_other
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id, post_id: params[:post_id])
  end

  def render_comment(comment)
    {
      body: comment.body,
      user_name: comment.user.name,
      timestamp: comment.created_at.strftime('%Y/%m/%d %H:%M:%S'),
      owned_by_current_user: comment.own?(current_user)
    }
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_text_alignment(comment, user)
    comment.own?(user) ? 'text-right' : 'text-left'
  end

  def comment_background_color(comment, user)
    comment.own?(user) ? 'bg-green-100' : 'bg-blue-100'
  end
end

app/views/comments/_comment.html.erb
<div class="flex flex-col space-y-2 p-1">
  <div class="flex items-start space-x-2 <%= comment.own?(current_user) ? 'flex-row-reverse' : '' %>">
    <div class="flex flex-col space-y-1 <%= comment_text_alignment(comment, current_user) %>">
      <p class="text-sm text-gray-500"><%= comment.user.name %></p>
      <p class="text-xs text-gray-400"><%= comment.created_at.strftime("%Y/%m/%d %H:%M") %></p>
      <div class="flex items-center">
        <div class="<%= comment_background_color(comment, current_user) %> rounded-xl p-2 mr-2">
          <p class="text-sm"><%= comment.body %></p>
        </div>
        <div>
          <% if comment.own?(current_user) %>
            <%= link_to post_comment_path(comment.post, comment), data: { turbo_method: :delete, turbo_confirm: 'コメントを削除しますか？' } do %>
            <i class="fa-regular fa-trash-can text-gray-400"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@post, @comment] do |f| %>
  <%= render 'shared/error_messages', object: @comment %>
  <div class="field">
    <%= f.label :body, 'コメント', class: "block text-left font-medium text-gray-700" %>
    <%= f.text_area :body, id: :comment_content, class: "mt-1 block w-full text-lg rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 border-gray-300", rows: 2 %>
  </div>

  <div class="actions mt-4">
    <%= f.submit "コメントを投稿", class: "w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
<% end %>