config/routes.rb
Rails.application.routes.draw do
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider

  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :users, only: %i[new create]
  resources :posts, only: %i[index new create show destroy] do
    collection do 
      get 'search'
    end
    
    member do
      get 'vote'
    end
    resources :comments, only: %i[create destroy]
    resources :votes, only: %i[create]
    mount ActionCable.server => '/cable'
    resources :comments, only: %i[create destroy]
  end

  resources :restaurants, only: %i[index] do
    collection do
      get 'search'
    end
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/views/shared/_before_login_header.html.erb
<header class="navbar bg-orange-50">
  <div class="flex-1 ml-3">
    <%= link_to 'Voteat', root_path, class: 'button text-2xl font-bold' %>
  </div>
  <div class="flex-none mr-3">
    <ul class="flex">
      <li class="mr-3"><%= link_to (t 'posts.index.title'), posts_path %></li>
      <li><%= link_to (t 'defaults.login'), login_path %></li>
    </ul>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'info' %>
    <div class="alert alert-info shadow-lg">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current flex-shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
        <span><%= message %></span>
      </div>
    </div>
  <% elsif message_type == 'success' %>
    <div class="alert alert-success shadow-lg">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <span><%= message %></span>
      </div>
    </div>
  <% elsif message_type == 'warning' %>
    <div class="alert alert-warning shadow-lg">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
        <span><%= message %></span>
      </div>
    </div>
  <% elsif message_type == 'error' %>
    <div class="alert alert-error shadow-lg">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <span><%= message %></span>
      </div>
    </div>
  <% end %>  
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-10 bg-orange-50">
  <div>
    <ul class="flex text-xs lg:text-base">
      <li class="mx-2"><%= link_to (t 'defaults.terms_of_use'), terms_path %></li>
      <li class="mx-2"><%= link_to (t 'defaults.privacy_policy'), privacy_path %></li>
      <li class="mx-2"><%= link_to (t 'defaults.contact'), 'https://forms.gle/p9GnF2wQhwhhztAZ8' %></li>
      <li><a href="http://webservice.recruit.co.jp/"><img src="http://webservice.recruit.co.jp/banner/hotpepper-m.gif" alt="ホットペッパー Webサービス" width="88" height="35" border="0" title="ホットペッパー Webサービス"></a></li>
      <p>【画像提供：ホットペッパー グルメ】</p>
    </ul>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="navbar bg-orange-50">
  <div class="flex-1 ml-3">
    <%= link_to 'Voteat', root_path, class: 'button text-2xl font-bold' %>
  </div>
  <div class="flex-none mr-3">
    <ul class="flex text-xs lg:text-base">
      <li class="mr-3"><%= link_to (t 'restaurants.search.title'), search_restaurants_path %></li>
      <li class="mr-3"><%= link_to (t 'posts.index.title'), posts_path %></li>
      <li><%= link_to (t 'defaults.logout'), logout_path, data: { turbo_method: :delete } %></li>
    </ul>
  </div>
</header>

app/views/shared/hotpepper_fetch_failed.html.erb
<div class="text-center my-16">
  <h2 class="text-2xl font-bold mb-4">店舗情報の取得に失敗しました</h2>
  <p class="mb-6">しばらくしてから再度お試しください。</p>
  <button class="btn" onclick="location.reload()">再読み込み</button>
</div>