config/routes.rb
Rails.application.routes.draw do
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider

  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :users, only: %i[new create]
  resources :posts, only: %i[index new create show destroy] do
    collection do 
      get 'search'
    end
    
    member do
      get 'vote'
    end
    resources :comments, only: %i[create destroy]
    resources :votes, only: %i[create]
    mount ActionCable.server => '/cable'
    resources :comments, only: %i[create destroy]
  end

  resources :restaurants, only: %i[index] do
    collection do
      get 'search'
    end
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :restaurants, dependent: :destroy
  has_many :votes, through: :restaurants
  accepts_nested_attributes_for :restaurants, allow_destroy: true,  reject_if: proc { |attributes| attributes['name'].blank? }


  validates :title, presence: true
  validate :at_least_one_restaurant

  def voted_by?(user)
    votes.exists?(user_id: user.id) 
  end

  private

  def at_least_one_restaurant
    errors.add(:base, '少なくとも1つのお店を選択してください') if restaurants.empty?
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[title created_at]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  skip_before_action :require_login, only: %i[index show]

  def new
    @post = Post.new
    @post.restaurants.build
    @store_informations = HotpepperSearchService.new.call(
      keyword: params[:keyword],
      address: params[:address]
    )
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = '投稿が作成されました。'
      redirect_to posts_path
    else
      @store_informations = HotpepperSearchService.new.call(
        keyword: params[:keyword],
        address: params[:address]
      )
      render :new
    end
  end
  

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path, success: t('.success'), status: :see_other
  end

  def show
    @post = Post.find(params[:id])
    @restaurants = @post.restaurants
    refresh_or_retry!(@restaurants)
    @restaurant_count = @restaurants.map { |restaurant| [restaurant.name, restaurant.votes.count] }.to_h
    max_votes = @restaurants.max_by { |restaurant| restaurant.votes.count }.votes.count
    @max_voted_restaurants = @restaurants.select { |restaurant| restaurant.votes.count == max_votes }
    @max_value = @restaurant_count.values.max
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :asc)
  end

  def vote
    @vote = Vote.new
    @post = Post.find(params[:id])
    @restaurants = Restaurant.where(post_id: @post.id)
    refresh_or_retry!(@restaurants)
  end

  private

  def post_params
    params.require(:post).permit(:title, restaurants_attributes: [:name, :image, :url, :external_shop_id])
  end

  def refresh_or_retry!(restaurants)
  attempts = params[:retry].to_i + 1

  HotpepperRefreshService.new.refresh_if_stale!(restaurants)
rescue => e
  Rails.logger.error("[HotpepperRefresh] #{e.class}: #{e.message}")

  if attempts <= 3
    # 少し待ってから再読み込み（例: 0.5秒）
    sleep 0.5
    redirect_to url_for(params.permit!.to_h.merge(retry: attempts)),
                alert: "店舗情報の取得に失敗しました。再読み込みします。(#{attempts}回目)"
  else
    render "errors/hotpepper_fetch_failed", status: :service_unavailable
  end
end
end

app/helpers/posts_helper.rb
module PostsHelper
  require 'net/http'
  require 'json'

  def get_hotpepper_res(keyword: nil, address: nil)
    uri = 'https://webservice.recruit.co.jp/hotpepper/gourmet/v1/'
    api_key = Rails.application.credentials.hotpepper_api_key
    url = uri << "?key=" << api_key << "&format=json" 

    if keyword
      url = url << "&keyword=" << URI.encode_www_form_component(keyword)
    end

    if address
      url = url << "&address=" << URI.encode_www_form_component(address)
    end

    res = Net::HTTP.get(URI.parse(url))
    parsed_json = JSON.parse(res)

    store_informations = parsed_json['results']['shop'] || []
  end
end

app/views/posts/_post.html.erb
<div class="p-4 w-full lg:w-1/3">
  <div class="card w-full h-101 bg-base-100 mx-auto my-6">
    <div class="card-body items-center text-center">
      <h2 class="card-title my-4 text-xl"><%= post.title %></h2>
      <figure><%= image_tag 'undraw_voting_nvu7.png' %></figure>
      <div class="flex justify-center">
        <%= link_to (t 'posts.index.voting_page'), vote_post_path(post), class: 'btn btn-xs lg:btn-sm bg-red-700 border-red-700 mx-1' %>
        <%= link_to (t 'posts.index.vote_result_page'), post_path(post), class: 'btn btn-xs lg:btn-sm bg-red-700 border-red-700 mx-1' %>
        <% if logged_in? && current_user.own?(post) %>
          <%= link_to post_path(post), data: { turbo_method: :delete, turbo_confirm: (t 'posts.index.vote_delete_confirm') } do %>
            <i class="fa-regular fa-trash-can lg:text-xl lg:pt-2"></i>
          <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="items-center py-12 px-4 min-h-screen">
  <h1 class="mb-14 text-center text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl"><%= t '.title' %></h1>
  <%= search_form_for @q, html: { class: "bg-white shadow-md rounded px-6 pt-4 pb-2 mb-4 flex items-center" } do |f| %>
  <div class="flex-grow mb-4">
    <%= f.label :title_cont, "タイトル検索", class: "block text-gray-700 font-bold mb-2" %>
    <%= f.search_field :title_cont, class: "shadow appearance-none border rounded w-full mr-2 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  <%= f.submit "検索", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded focus:outline-none focus:shadow-outline" %>
  <% end %>

  <% if @posts.present? %>
    <div class="flex flex-wrap">
      <%= render @posts %>
    </div>
  <% else %>
    <div class="text-center">
      <p class="text-2xl sm:text-3xl"><%= t '.no_result' %></p>
    </div>
  <% end %>
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="flex justify-center items-center py-12 px-4">
  <div class="lg:w-1/2 md:w-2/3 mx-auto text-center  min-h-screen">
    <h1 class="my-6 text-center text-3xl font-bold tracking-tight text-gray-900"><%= t ('.title') %></h1>
      <%= form_with model: @post, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="form-control mb-10">
          <%= f.label :title, class: 'label' %>
          <%= f.text_field :title, required: true ,class: 'input input-bordered' %>
        </div>
        <% if @store_informations.empty? %>
          <p class="text-2xl my-10">検索結果が0件です</p>
          <%= link_to (t '.re_restaurant_search'),  search_restaurants_path, class: 'btn bg-red-600 border-red-600' %>
        <% else %>
        <p class="mb-10 text-xl">投票したいお店を選択してください</p>
        <% @store_informations.each do |info| %>
          <%= f.fields_for :restaurants do |restaurant_form| %>
            <div class="form-contol flex items-center justify-between mb-5 text-center">
              <%= image_tag info['photo']['mobile']['l'] %>
              <%= link_to info['name'], info['urls']['pc'], class: 'text-blue-700 text-base lg:text-xl', target: :_blank, rel: 'noopener noreferrer' %>
              <%= restaurant_form.hidden_field :external_shop_id, value: info['id'] %>
              <%= restaurant_form.check_box :name, { class: 'w-5 h-5' }, info['name'], false %>
              <%= restaurant_form.hidden_field :image, value: info['photo']['mobile']['l'] %>
              <%= restaurant_form.hidden_field :url, value: info['urls']['pc'] %>
            </div>
          <% end %>
        <% end %>
        <p class="mb-5 mt-20 text-xl">こちらからも飲食店を追加できます</p>
        <div class="form-control mb-5">
          <%= f.fields_for :restaurants do |restaurant_form| %>
            <%= restaurant_form.label :name, class: 'label' %>
            <%= restaurant_form.text_field :name, class: 'input input-bordered' %>
          <% end %>
        </div>
        <div class="form-control my-5">
          <%= f.fields_for :restaurants do |restaurant_form| %>
            <%= restaurant_form.text_field :name, class: 'input input-bordered' %>
          <% end %>
        </div>
        <div class="form-control my-5">
          <%= f.fields_for :restaurants do |restaurant_form| %>
            <%= restaurant_form.text_field :name, class: 'input input-bordered' %>
          <% end %>
        </div>
          <div class="flex flex-col justify-center">
            <div>
              <%= f.submit (t '.create'), class: 'btn btn-primary mt-10' %>
            </div>
            <div class="flex justify-between mt-12">
              <%= link_to (t '.re_restaurant_search'),  search_restaurants_path, class: 'btn bg-red-600 border-red-600 mr-10 lg:mr-0' %>
            </div>
          </div>
        <% end %> 
      <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="flex justify-center items-center py-12 px-4"> 
  <div class="lg:w-1/2 md:w-2/3 mx-auto text-center  min-h-screen">
    <h1 class="my-6 text-center text-3xl font-bold tracking-tight text-gray-900"><%= t ('.title') %></h1>
    <h1 class="my-6 text-center text-3xl font-bold tracking-tight text-gray-900"><%= @post.title %></h1>
    <% if @restaurant_count.empty? %>
      <p class="text-xl my-3"><%= t('.no_vote_results') %></p>
    <% else %>
    <div class="w-full lg:hidden">
      <%= bar_chart @restaurant_count, empty: "投票結果がありません", height: "800px", width: "300px", library: { 
        yAxis: {
          max: @max_value,
          allowDecimals: false
        },
        legend: {
          enabled: false
        },
        chart: {
          height: 800
        },
        xAxis: {
          labels: {
            style: {
              textOverflow: 'none',
            },
          }
        }
        } %>
      </div>

    <div class="w-full hidden lg:block">
      <%= bar_chart @restaurant_count, empty: "投票結果がありません", height: "500px", library: { 
        yAxis: {
          max: @max_value,
          allowDecimals: false
        },
        legend: {
          enabled: false
        },
        chart: {
          height: 500
        },
        xAxis: {
          labels: {
            style: {
              textOverflow: 'none',
            },
          }
        }
        } %>
      </div>
      <div class="mt-20">
        <p class="text-2xl py-2"><%= t('.most_voted_restaurant') %></p>
        <% @max_voted_restaurants.each do |max_restaurant| %>
          <p class="text-xl text-blue-700 py-2"><%= link_to max_restaurant.name, max_restaurant.url, target: :_blank, rel: 'noopener noreferrer' %></p>
        <% end %>
      </div>

      <div class="mt-12">
        <p class="text-2xl">コメント一覧</p>
        <div id="comments" class="mx-auto w-[300px] lg:w-[400px]">
          <%= render @comments %>
        </div>
      </div>
        
      <div class="my-12 p-4">
        <%= render 'comments/form', post: @post, comment: @comment %>
      </div>

    <% end %>
    <%= link_to (t '.vote_list_page'), posts_path, class: 'btn bg-red-600 border-red-600 mt-12' %>
  </div>
</div>

app/views/posts/vote.html.erb
<div class="flex justify-center items-center py-12 px-4">
  <div class="lg:w-1/2 md:w-2/3 mx-auto text-center  min-h-screen">
    <h1 class="my-6 text-center text-4xl font-bold tracking-tight text-gray-900">投票ページ</h1>
    <h3 class="my-6 text-center text-2xl font-bold tracking-tight text-gray-900"><%= @post.title %></h3>
    <p class="mb-10 text-xl">お店を選んで投票してください</p>
    <%= form_with model: @vote, url: post_votes_path(@post), local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <% @restaurants.each do |restaurant| %>
  <div class="form-contol flex items-center justify-between mb-5 text-center">
    <% if restaurant.image.present? %>
      <%= image_tag restaurant.image %>
    <% else %>
      <div class="w-22 h-20"></div>
    <% end %>
  
    <% if restaurant.url.present? %>
      <%= link_to restaurant.name, restaurant.url, class: 'text-blue-700 text-base lg:text-xl', target: :_blank, rel: 'noopener noreferrer' %>
    <% else %>
      <%= f.label restaurant.name, class: 'text-base lg:text-xl' %>
    <% end %>
    <%= f.radio_button :restaurant_id, restaurant.id, class: 'w-5 h-5' %>
  </div>
<% end %>

      <%= f.submit (t '.voting'), class: 'btn btn-primary mt-6' %>
    <% end %>
  </div>
</div>