config/routes.rb
Rails.application.routes.draw do
  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider

  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :users, only: %i[new create]
  resources :posts, only: %i[index new create show destroy] do
    collection do 
      get 'search'
    end
    
    member do
      get 'vote'
    end
    resources :comments, only: %i[create destroy]
    resources :votes, only: %i[create]
    mount ActionCable.server => '/cable'
    resources :comments, only: %i[create destroy]
  end

  resources :restaurants, only: %i[index] do
    collection do
      get 'search'
    end
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to search_restaurants_path, success: t('.success')
    else
      flash.now[:error] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end

app/views/user_sessions/new.html.erb
<div class="flex justify-center items-center py-12 px-4">
  <div class="lg:w-1/2 md:w-2/3 min-h-screen mx-auto">
    <h1 class="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900"><%= t '.title' %></h1>
    <%= form_with url: login_path, method: :post, local: true do |f| %>
      <div class="form-control mb-10">
        <%= f.label :email, User.human_attribute_name(:email) ,class: 'label' %>
        <%= f.email_field :email, class: 'input input-bordered' %>
      </div>
      <div class="form-control mb-10">
        <%= f.label :password, User.human_attribute_name(:password) ,class: 'label' %>
        <%= f.password_field :password, class: 'input input-bordered' %>
      </div>
      <div class="flex justify-between items-center">
        <%= f.submit (t 'defaults.login'), class: 'btn btn-primary' %>
        <%= link_to (t '.register_page'), new_user_path, class: 'inline-block text-sm lg:text-base' %>
      </div>
    <% end %>

    <div class="text-center my-8">
      <p class="text-gray-600 text-sm lg:text-base">またはLINEでログイン</p>
    </div>
    <div class="flex justify-center">
      <div>
        <%= link_to auth_at_provider_path(provider: :line) do %>
        <%= image_tag 'btn_login_base.png', alt: 'LINEでログイン' %>
        <% end %>
      </div>
    </div>
  </div>
</div>